code_type: "php"
name: |-
   Переопределение классов сущностей	
description: |-
   библиотека показывает как можно переопределить классы сущностей. Для того что бы это работало в коде IN необходиом делать return этих новых обектов
    
